spring:
  config:
    activate:
      on-profile: openai
  ai:
    model:
      chat: openai
    openai:
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      api-key: ${OPENAI_API_KEY}
      chat:
        model: ${OPENAI_CHAT_MODEL}
